#https://help.appveyor.com/discussions/questions/4148-why-does-appveyor-seem-not-to-pick-up-my-appveyoryml
version: 1.0.{build}
image: Visual Studio 2017
install:
- ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex
build_script:
- ps: >-
    Vsix-IncrementVsixVersion | Vsix-UpdateBuildVersion;

    nuget restore -verbosity quiet;

    msbuild /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m;
after_test:
- ps: Vsix-PushArtifacts | Vsix-PublishToGallery
